# описания сервисов (контейнеров), которые должны быть развёрнуты
services:
  # описание контейнера db
  db: # имя сервиса
    # образ, из которого должен быть запущен контейнер
    image: postgres:16.1
    # имя, которое нужно присвоить контейнеру
    container_name: postgres
    # публикуемые порты
    ports:
      - "5431:5432"
    # настройки монтирования volume
    volumes:
      - ./volumes/postgres-stats:/var/lib/postgresql/data/
    # переменные окружения
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      # указываем, какую команду выполнить внутри контейнера для проверки его статуса
      # в этом примере вызывается утилита pg_isready, входящая в состав PostgreSQL
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      # через какое время после запуска начинать проверку
      timeout: 5s
      # интервал повторов проверки
      interval: 5s
      # количество попыток
      retries: 10
  db2: # имя сервиса
    # образ, из которого должен быть запущен контейнер
    image: postgres:16.1
    # имя, которое нужно присвоить контейнеру
    container_name: postgres2
    # публикуемые порты
    ports:
      - "5433:5432"
    # настройки монтирования volume
    volumes:
      - ./volumes/postgres-main:/var/lib/postgresql/data/
    # переменные окружения
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      # указываем, какую команду выполнить внутри контейнера для проверки его статуса
      # в этом примере вызывается утилита pg_isready, входящая в состав PostgreSQL
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      # через какое время после запуска начинать проверку
      timeout: 5s
      # интервал повторов проверки
      interval: 5s
      # количество попыток
      retries: 10