version: '3.8'
services:
  stats-server:
    build: ./ewm-stats/ewm-stats-service
    image: ewm-stats-server-image
    container_name: ewm-stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats

  stats-db:
    image: postgres:16.1
    container_name: ewm-stats-service-db-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
